### ISSUE TITLE
help!安装出错,未知原因! Class File Lose

### ISSUE THREAD

**Issue by iwinder** [lazyphp/PESCMS-DOC#2]
到80%的时候报了下面的错误。。

> 安装出错,未知原因!
> 
> 
> 
> Class File Lose
> 
>                                           
> Debug info:
> Class undefined.                            
> File : 
> /~~~/PESCMS/Model/Extra.class.php
>                        
> 
> 当前PHP环境有扩展加载失败
> 
> 
> 
> 请访问本链接获取解决方案
> 
> 等待响应.................................................................................
> 
> 执行安装程序...

**Comment by lazyphp** [comment]
请重新下载程序，最近提交的代码有严重的错误。
或者下载此版本的：https://github.com/lazyphp/PESCMS-DOC/tree/1.3.7

**Comment by iwinder** [comment]
1.37分支和master有什么区别么？我之前直接下载的master的

**Comment by lazyphp** [comment]
1.3.7是之前的稳定版。你今天下载master分支由于之前我更新了代码，没做测试所以安装时就报错了。现在我已经把master回滚了一个可用的commit了。
而masert当前分支和1.3.7区别在于，修复了一些BUG。

**Comment by iwinder** [comment]
嗯呢，好的，知道了，谢啦
